// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Encounter, EncounterData, EncounterTableId } from "./tables/Encounter.sol";
import { Hero, HeroData, HeroTableId } from "./tables/Hero.sol";
import { Monsters, MonstersData, MonstersTableId } from "./tables/Monsters.sol";
import { EncounterTrigger, EncounterTriggerTableId } from "./tables/EncounterTrigger.sol";
import { Encounterable, EncounterableTableId } from "./tables/Encounterable.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
