// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMonsterSystem {
  function generate(string memory image) external;

  function getMonster(uint256 _id) external returns (string memory);
}
