// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMonsterSystem {
  function generate(string memory image, uint32 x, uint32 y) external;

  function fight(uint256 _id) external;
}
